# Generated by Django 3.2.7 on 2021-10-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_frinedly_name_category_friendly_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
